initialize
{
    options:
    {
        withDomLvl1: true,
            normalizeWhitespace
    :
        false,
            xml
    :
        false,
            decodeEntities
    :
        true
    }
,
    _root:
        initialize
    {
        '0'
    :
        {
            type: 'root',
                name
        :
            'root',
                namespace
        :
            'http://www.w3.org/1999/xhtml',
                attribs
        :
            {
            }
        ,
            'x-attribsNamespace'
        :
            {
            }
        ,
            'x-attribsPrefix'
        :
            {
            }
        ,
            children: [Array],
                parent
        :
            null,
                prev
        :
            null,
                next
        :
            null
        }
    ,
        options:
        {
            withDomLvl1: true,
                normalizeWhitespace
        :
            false,
                xml
        :
            false,
                decodeEntities
        :
            true
        }
    ,
        length: 1,
            _root
    :
        [Circular]
    }
,
    length: 0,
        prevObject
:
    initialize
    {
        '0'
    :
        {
            type: 'root',
                name
        :
            'root',
                namespace
        :
            'http://www.w3.org/1999/xhtml',
                attribs
        :
            {
            }
        ,
            'x-attribsNamespace'
        :
            {
            }
        ,
            'x-attribsPrefix'
        :
            {
            }
        ,
            children: [Array],
                parent
        :
            null,
                prev
        :
            null,
                next
        :
            null
        }
    ,
        options:
        {
            withDomLvl1: true,
                normalizeWhitespace
        :
            false,
                xml
        :
            false,
                decodeEntities
        :
            true
        }
    ,
        length: 1,
            _root
    :
        [Circular]
    }
}